[build]
  base = "ai-recruit-frontend"
  command = "npm install -g pnpm && pnpm install && pnpm generate:recruiter"
  publish = "apps/recruiter-dashboard/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
