[build]
  command = "npm install -g pnpm && cd ai-recruit-frontend && pnpm install --frozen-lockfile && pnpm generate:recruiter"
  publish = "ai-recruit-frontend/apps/recruiter-dashboard/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
