[build]
  base = "ai-recruit-frontend/apps/recruiter-dashboard"
  command = "npm install && npm run generate"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NUXT_PUBLIC_API_BASE = "https://jsonplaceholder.typicode.com"
  NUXT_PUBLIC_WS_URL = "wss://echo.websocket.org"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
