[build]
  # Remove the base directory to build from repo root
  command = "cd ai-recruit-frontend && npm install -g pnpm && pnpm install && pnpm build:recruiter"
  publish = "ai-recruit-frontend/apps/recruiter-dashboard/.output/public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
