[build]
  base = "ai-recruit-frontend/apps/recruiter-dashboard"
  command = """
    echo "Removing workspace files to avoid npm workspace detection..." &&
    rm -f ../../package.json ../../pnpm-workspace.yaml &&
    echo "Installing dependencies without workspace context..." &&
    npm install --no-workspaces --legacy-peer-deps &&
    echo "Running generate..." &&
    npm run generate
  """
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
