[build]
  base = "ai-recruit-frontend/apps/recruiter-dashboard" 
  command = """
    echo "Installing with workspace disabled..." &&
    npm install --no-workspaces --force &&
    echo "Generating static site..." &&
    npm run generate
  """
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_WORKSPACES = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
