[build]
  command = "cd ai-recruit-frontend && npm install -g pnpm && pnpm install && pnpm --filter @ai-recruit/recruiter-dashboard generate"
  publish = "ai-recruit-frontend/apps/recruiter-dashboard/.output/public"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
