[build]
  command = """
    echo "Creating isolated build environment..." &&
    mkdir -p /tmp/build &&
    cp -r ai-recruit-frontend/apps/recruiter-dashboard/* /tmp/build/ &&
    cd /tmp/build &&
    echo "Installing in isolated environment..." &&
    npm install &&
    echo "Building..." &&
    npm run generate &&
    echo "Copying build output back..." &&
    cp -r dist/* /opt/build/repo/netlify-output/
  """
  publish = "netlify-output"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
