[build]
  base = "ai-recruit-frontend/apps/recruiter-dashboard"
  command = "yarn install && yarn generate"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=/dev/null"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
