[build]
  base = "ai-recruit-frontend/apps/recruiter-dashboard"
  command = """
    echo "Using Yarn to avoid npm workspace issues..." &&
    npm install -g yarn &&
    yarn install --ignore-workspace-root-check &&
    yarn generate
  """
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
