[build]
  command = "cd ai-recruit-frontend && npm install -g pnpm@8.15.0 && pnpm install && pnpm generate:recruiter"
  publish = "ai-recruit-frontend/apps/recruiter-dashboard/dist"

[build.environment]
  NODE_VERSION = "20"
  NUXT_PUBLIC_API_BASE = "https://jsonplaceholder.typicode.com"
  NUXT_PUBLIC_WS_URL = "wss://echo.websocket.org"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
